version: '3.8'

services:
  web:
    build: .
    command: sh -c "alembic upgrade head && gunicorn --bind :8000 --workers 1 --worker-class uvicorn.workers.UvicornWorker --factory --threads 8 app.main:run"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.docker.env
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.docker.env
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    env_file:
      - ./.docker.env