version: '3.8'

services:
  web:
    build: .
    command: python main.py
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.docker.env
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.docker.env
  redis:
    image: redis:alpine
    ports:
      - 6379:6379